version: '3'
services:
  scandelapp:
    build:
      context: ./scandelapp
      dockerfile: Dockerfile
    ports:
      - 2000:2000
    volumes:
      - ./scandelapp:/prod_scandelapp

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - 6000:6000
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./database:/prod_scandelapp