version: '3'
services:
  dev.scandela:
    build:
      context: ./scandelapp
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./scandelapp:/dev_env
    environment:
      - CHOKIDAR_USEPOLLING=true    # For specific OS like Windows and MacOs
  
  server_dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./server:/dev_env
