version: '3'
services:
  app.scandela:
    build:
      context: ./scandelapp
      dockerfile: Dockerfile.dev
    ports:
      - 2000:2000
    volumes:
      - ./scandelapp:/app
    environment:
      - CHOKIDAR_USEPOLLING=true    # For specific OS like Windows and MacOs