version: '3'
services:
  scandelapp_dev:
    build:
      context: ./scandelapp
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./scandelapp:/app
    environment:
      - CHOKIDAR_USEPOLLING=true    # For specific OS like Windows and MacOs
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
   #   depends_on:
   #     - db

  # db:
  #   image: .......
  #   ports:
  #     - .......
  #   environment:
  #     - DB_ROOT_PASSWORD=your_password
  #     - DB_DATABASE=your_database

  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./jenkins:/var/jenkins_home