version: '3'
services:
  dev.scandela:
    build:
      context: ./scandelapp
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./scandelapp:/dev_scandelapp
  
  # dev.server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 3001:3001

  dev-database:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    ports:
      - 4001:4001
    volumes:
      - ./database:/dev_scandelapp