version: '3'
services:
  scandelapp:
    build:
      context: ./scandelapp
      dockerfile: Dockerfile
    ports:
      - 2000:2000
    volumes:
      - ./scandelapp:/app
    environment:
      - CHOKIDAR_USEPOLLING=true    # For specific OS like Windows and MacOs
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./server:/app

  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./jenkins:/var/jenkins_home