export let optimisationTemplateDataBackup = [
    {
        id: 0,
        saved: false,
        selected: false,
        name: 'EPVT008004',
        type: 'Changement bulbe',
        location: 'Rue de la Garouère',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'RIVIERA 2',
        height: 9,
        validate: null as null,
    },
    {
        id: 1,
        saved: false,
        selected: false,
        name: 'EPVT142013',
        type: 'Changement bulbe',
        location: 'Rue du Domaine',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 6,
        validate: null as null,
    },
    {
        id: 2,
        saved: false,
        selected: false,
        name: 'EPST067013',
        type: 'Changement bulbe',
        location: 'Chemin du Tribois',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 9',
        height: 8,
        validate: null as null,
    },
    {
        id: 3,
        saved: false,
        selected: false,
        name: 'EPVT157029',
        type: 'Changement bulbe',
        location: 'Rue des Goldens',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'HARMONY FDL/D2/VP',
        height: 8,
        validate: null as null,
    },
    {
        id: 4,
        saved: false,
        selected: false,
        name: 'EPOR032059',
        type: 'Changement bulbe',
        location: 'Rue Albert Einstein',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ESTORIL P',
        height: 8,
        validate: null as null,
    },
    {
        id: 5,
        saved: false,
        selected: false,
        name: 'EPST003021',
        type: 'Changement bulbe',
        location: 'Rue Robert Douineau',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'PILOTE T1',
        height: 8,
        validate: null as null,
    },
    {
        id: 6,
        saved: false,
        selected: false,
        name: 'EPVT074002',
        type: 'Changement bulbe',
        location: 'Avenue du Clos du Vallon',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'KIO',
        height: 4,
        validate: null as null,
    },
    {
        id: 7,
        saved: false,
        selected: false,
        name: 'EPRZ086003',
        type: 'Changement bulbe',
        location: 'Rue Jean Baptiste Kléber',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ECLAT',
        height: 4,
        validate: null as null,
    },
    {
        id: 8,
        saved: false,
        selected: false,
        name: 'EPOR048035',
        type: 'Changement bulbe',
        location: 'Rue de la Rigotière',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 8,
        validate: null as null,
    },
    {
        id: 9,
        saved: false,
        selected: false,
        name: 'EPVT053031',
        type: 'Changement bulbe',
        location: 'Rue des Primeurs',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'KIO',
        height: 3.5,
        validate: null as null,
    },
    {
        id: 10,
        saved: false,
        selected: false,
        name: 'EPRZ067037',
        type: 'Changement bulbe',
        location: 'Promenade Georges Colder',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ALURA',
        height: 3.5,
        validate: null as null,
    },
    {
        id: 11,
        saved: false,
        selected: false,
        name: 'EPVT011023',
        type: 'Changement bulbe',
        location: 'Rue de la Basse Canterie',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'COMETE LV2',
        height: 8,
        validate: null as null,
    },
    {
        id: 12,
        saved: false,
        selected: false,
        name: 'EPST005056',
        type: 'Changement bulbe',
        location: "Rue d'Azay le Rideau",
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'COMETE LV1',
        height: 6,
        validate: null as null,
    },
    {
        id: 13,
        saved: false,
        selected: false,
        name: 'EPBO117030',
        type: 'Changement bulbe',
        location: 'Rue de la Ravardière',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 0,
        validate: null as null,
    },
    {
        id: 14,
        saved: false,
        selected: false,
        name: 'EPRZ088007',
        type: 'Changement bulbe',
        location: 'Rue Alexandre Huchon',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'EUROPA',
        height: 8,
        validate: null as null,
    },
    {
        id: 15,
        saved: false,
        selected: false,
        name: 'EPVT024001',
        type: 'Changement bulbe',
        location: 'Rue des Lavandières',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'SAPHIR 1',
        height: 7,
        validate: null as null,
    },
    {
        id: 16,
        saved: false,
        selected: false,
        name: 'EPOR027047',
        type: 'Changement bulbe',
        location: 'Rue de Locarec',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ESTORIL P',
        height: 8,
        validate: null as null,
    },
    {
        id: 17,
        saved: false,
        selected: false,
        name: 'EPRZ038063',
        type: 'Changement bulbe',
        location: 'Rue Jean Jaurès',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'ALYRIA',
        height: 6,
        validate: null as null,
    },
    {
        id: 18,
        saved: false,
        selected: false,
        name: 'EPVT113033',
        type: 'Changement bulbe',
        location: 'Impasse Auguste Saupin',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MINI CITYSOUL',
        height: 5,
        validate: null as null,
    },
    {
        id: 19,
        saved: false,
        selected: false,
        name: 'EPVT056010',
        type: 'Changement bulbe',
        location: 'Rue du Clos des Vignes',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'RIVIERA 2',
        height: 8,
        validate: null as null,
    },
    {
        id: 20,
        saved: false,
        selected: false,
        name: 'EPSH132079',
        type: 'Allumer lampadaire',
        location: 'Allée William Harvey',
        description: 'Coucher du soleil à 21:47',
        solution: 'Allumer le lampadaire EPSH132079 à partir de 21:47',
        lampType: 'SHP',
        foyerType: 'ELYXE',
        height: 4,
        validate: null as null,
    },
    {
        id: 21,
        saved: false,
        selected: false,
        name: 'EPSH132079',
        type: 'Éteindre lampadaire',
        location: 'Allée William Harvey',
        description: 'Lever du soleil à 06:20',
        solution: 'Éteindre le lampadaire EPSH132079 à partir de 06:20',
        lampType: 'SHP',
        foyerType: 'ELYXE',
        height: 4,
        validate: null as null,
    },
    {
        id: 22,
        saved: false,
        selected: false,
        name: 'EPCA006030',
        type: 'Ajouter lampadaire',
        location: 'Avenue de Chinon',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,273 ; LatMax: 47,273 ; LongMin: -1,483 ; LongMax: -1,483',
        lampType: 'SHP',
        foyerType: 'GAMMA',
        height: 3.5,
        validate: null as null,
    },
    {
        id: 23,
        saved: false,
        selected: false,
        name: 'EPNA341018',
        type: 'Ajouter lampadaire',
        location: 'Rue de Goulphar',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,279 ; LatMax: 47,279 ; LongMin: -1,510 ; LongMax: -1,510',
        lampType: 'LED',
        foyerType: 'R2L2',
        height: 3.5,
        validate: null as null,
    },
    {
        id: 24,
        saved: false,
        selected: false,
        name: 'EPNA093029',
        type: 'Ajouter lampadaire',
        location: 'Rue de la Convention',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,210 ; LatMax: 47,210 ; LongMin: -1,596 ; LongMax: -1,595',
        lampType: 'LED',
        foyerType: 'AMPERA',
        height: 5.4,
        validate: null as null,
    },
    {
        id: 25,
        saved: false,
        selected: false,
        name: 'EPSL034039',
        type: 'Ajouter lampadaire',
        location: 'Rue du Professeur René Auvigne',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,251 ; LatMax: 47,251 ; LongMin: -1,493 ; LongMax: -1,493',
        lampType: 'SHP',
        foyerType: 'KIO',
        height: 3.8,
        validate: null as null,
    },
    {
        id: 26,
        saved: false,
        selected: false,
        name: 'EPCH014015',
        type: 'Ajouter lampadaire',
        location: 'Rue Hector Berlioz',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,292 ; LatMax: 47,293 ; LongMin: -1,559 ; LongMax: -1,559',
        lampType: 'SHP',
        foyerType: 'RIVIERA 1',
        height: 8,
        validate: null as null,
    },
    {
        id: 27,
        saved: false,
        selected: false,
        name: 'EPVT044004',
        type: 'Ajouter lampadaire',
        location: 'Rue des Grands Fosses',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,180 ; LatMax: 47,181 ; LongMin: -1,442 ; LongMax: -1,442',
        lampType: 'SHP',
        foyerType: 'SAPHIR 1',
        height: 8,
        validate: null as null,
    },
    {
        id: 28,
        saved: false,
        selected: false,
        name: 'EPCH008057',
        type: 'Ajouter lampadaire',
        location: 'Allée des Meldeniers',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,307 ; LatMax: 47,308 ; LongMin: -1,541 ; LongMax: -1,541',
        lampType: 'SHP',
        foyerType: 'URBANA FOREST',
        height: 3.5,
        validate: null as null,
    },
    {
        id: 29,
        saved: false,
        selected: false,
        name: 'EPCH078047',
        type: 'Ajouter lampadaire',
        location: 'Rue Rogatien Levesque',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,295 ; LatMax: 47,296 ; LongMin: -1,552 ; LongMax: -1,551',
        lampType: 'SHP',
        foyerType: 'KIO CLASSE II',
        height: 4.5,
        validate: null as null,
    },
    {
        id: 30,
        saved: false,
        selected: false,
        name: 'EPSO037027',
        type: 'Ajouter lampadaire',
        location: 'Rue des Genêts',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,142 ; LatMax: 47,143 ; LongMin: -1,530 ; LongMax: -1,530',
        lampType: 'LED',
        foyerType: 'FLOW',
        height: 4.5,
        validate: null as null,
    },
    {
        id: 31,
        saved: false,
        selected: false,
        name: 'EPBG031012',
        type: 'Ajouter lampadaire',
        location: 'Rue Simone De Beauvoir',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,203 ; LatMax: 47,203 ; LongMin: -1,471 ; LongMax: -1,471',
        lampType: 'LED',
        foyerType: 'YOA',
        height: 4,
        validate: null as null,
    },
    {
        id: 32,
        saved: false,
        selected: false,
        name: 'EPOR089024',
        type: 'Ajouter lampadaire',
        location: 'Rue Charles Richet',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,246 ; LatMax: 47,247 ; LongMin: -1,595 ; LongMax: -1,595',
        lampType: 'SHP',
        foyerType: 'ORIENT',
        height: 3.5,
        validate: null as null,
    },
    {
        id: 33,
        saved: false,
        selected: false,
        name: 'EPSH105029',
        type: 'Ajouter lampadaire',
        location: 'Rue Jacques Cartier',
        description: "La distance entre 2 lampadaire n'est pas respectée.",
        solution:
            'Ajouter un lampadaire dans le rayon: LatMin: 47,226 ; LatMax: 47,226 ; LongMin: -1,636 ; LongMax: -1,635',
        lampType: 'SHP',
        foyerType: 'EOLE',
        height: 4,
        validate: null as null,
    },
    {
        id: 34,
        saved: false,
        selected: false,
        name: 'EPBY006037',
        type: 'Retirer lampadaire',
        location: 'Rue de Pornic',
        description: "La distance entre les lampadaires n'est pas optimale.",
        solution:
            'Retirer le lampadaire EPBY006037 car trop proche des lampadaires EPBY006036, EPBY006037',
        lampType: 'SHP',
        foyerType: 'PILOTE T2',
        height: 9,
        validate: null as null,
    },
    {
        id: 35,
        saved: false,
        selected: false,
        name: 'EPSH105067',
        type: 'Retirer lampadaire',
        location: 'Rue Océane',
        description: "La distance entre les lampadaires n'est pas optimale.",
        solution:
            'Retirer le lampadaire EPSH105067 car trop proche des lampadaires EPSH105067, EPSH105068',
        lampType: 'SHP',
        foyerType: 'CITYSOUL MINI',
        height: 7,
        validate: null as null,
    },
    {
        id: 36,
        saved: false,
        selected: false,
        name: 'EPSO058030',
        type: 'Retirer lampadaire',
        location: 'Rue des Sports',
        description: "La distance entre les lampadaires n'est pas optimale.",
        solution:
            'Retirer le lampadaire EPSO058030 car trop proche des lampadaires EPSO058030, EPSO058029',
        lampType: 'IM',
        foyerType: 'IRIDIUM',
        height: 4.5,
        validate: null as null,
    },
    {
        id: 37,
        saved: false,
        selected: false,
        name: 'EPBO064013',
        type: 'Retirer lampadaire',
        location: 'Chemin de la Buissonnière',
        description: "La distance entre les lampadaires n'est pas optimale.",
        solution:
            'Retirer le lampadaire EPBO064013 car trop proche des lampadaires EPBO064013, EPBO064009',
        lampType: 'IMC',
        foyerType: 'NEOS 2',
        height: 11,
        validate: null as null,
    },
    {
        id: 38,
        saved: false,
        selected: false,
        name: 'EPBO053012',
        type: 'Retirer lampadaire',
        location: 'Rue de la Chapelle',
        description: "La distance entre les lampadaires n'est pas optimale.",
        solution:
            'Retirer le lampadaire EPBO053012 car trop proche des lampadaires EPBO053012, EPBO053045',
        lampType: 'SHP',
        foyerType: 'CITEA MINI',
        height: 5,
        validate: null as null,
    },
    {
        id: 39,
        saved: false,
        selected: false,
        name: 'EPNA046029',
        type: 'Réduire intensité lampadaire',
        location: 'Rue de la Persévérance',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 0.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'LED',
        foyerType: 'ISARO',
        height: 0,
        validate: null as null,
    },
    {
        id: 40,
        saved: false,
        selected: false,
        name: 'EPNA027088',
        type: 'Réduire intensité lampadaire',
        location: 'Rue de la Papotière',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 0.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'LED',
        foyerType: 'IRIDIUM 10',
        height: 0,
        validate: null as null,
    },
    {
        id: 41,
        saved: false,
        selected: false,
        name: 'EPCH004014',
        type: 'Réduire intensité lampadaire',
        location: 'Boulevard Henri Becquerel',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 20.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'LED',
        foyerType: 'DISCERA 600',
        height: 8,
        validate: null as null,
    },
    {
        id: 42,
        saved: false,
        selected: false,
        name: 'EPCH131005',
        type: 'Réduire intensité lampadaire',
        location: "Rue de l'Europe",
        description:
            'Le lampdaire est entouré par 3 lampadaire(s) dans un rayon de 20.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 15% afin d'économiser de l'énergie.",
        lampType: 'SHP',
        foyerType: 'ORATEC 55',
        height: 8,
        validate: null as null,
    },
    {
        id: 43,
        saved: false,
        selected: false,
        name: 'EPCA021049',
        type: 'Réduire intensité lampadaire',
        location: 'Rue du Taile',
        description:
            'Le lampdaire est entouré par 2 lampadaire(s) dans un rayon de 15.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 10% afin d'économiser de l'énergie.",
        lampType: 'LED',
        foyerType: 'IRIDIUM 10',
        height: 6,
        validate: null as null,
    },
    {
        id: 44,
        saved: false,
        selected: false,
        name: 'EPLM024044',
        type: 'Réduire intensité lampadaire',
        location: 'Rue Violin',
        description:
            'Le lampdaire est entouré par 2 lampadaire(s) dans un rayon de 15.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 10% afin d'économiser de l'énergie.",
        lampType: 'LED',
        foyerType: 'AMPERA',
        height: 6,
        validate: null as null,
    },
    {
        id: 45,
        saved: false,
        selected: false,
        name: 'EPSH209045',
        type: 'Réduire intensité lampadaire',
        location: 'Boulevard Winston Churchill',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 20.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'SHP',
        foyerType: 'ESTORIL G',
        height: 8,
        validate: null as null,
    },
    {
        id: 46,
        saved: false,
        selected: false,
        name: 'EPNA083068',
        type: 'Réduire intensité lampadaire',
        location: 'Rue du Bouillon',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 0.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'LED',
        foyerType: 'AMPERA',
        height: 0,
        validate: null as null,
    },
    {
        id: 47,
        saved: false,
        selected: false,
        name: 'EPSH119133',
        type: 'Réduire intensité lampadaire',
        location: 'Rue James Cook',
        description:
            'Le lampdaire est entouré par 6 lampadaire(s) dans un rayon de 20.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 20% afin d'économiser de l'énergie.",
        lampType: 'SHP',
        foyerType: 'DIAMANT SNF 100',
        height: 8,
        validate: null as null,
    },
    {
        id: 48,
        saved: false,
        selected: false,
        name: 'EPVT053099',
        type: 'Réduire intensité lampadaire',
        location: "Rue de la Grand' Maison",
        description:
            'Le lampdaire est entouré par 2 lampadaire(s) dans un rayon de 22.5m.',
        solution:
            "Réduire l'intensité du lampadaire de 10% afin d'économiser de l'énergie.",
        lampType: 'SHP',
        foyerType: 'MODENA',
        height: 9,
        validate: null as null,
    },
    {
        id: 49,
        saved: false,
        selected: false,
        name: 'EPVT019002',
        type: 'Réduire intensité lampadaire',
        location: 'Route de Saint-Fiacre',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 20.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'LED',
        foyerType: 'ISARO LED',
        height: 8,
        validate: null as null,
    },
    {
        id: 50,
        saved: false,
        selected: false,
        name: 'EPVT008052',
        type: 'Réduire intensité lampadaire',
        location: 'Allée des Hauts Viviers',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 12.5m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'SHP',
        foyerType: 'ELIPT 345',
        height: 5,
        validate: null as null,
    },
    {
        id: 51,
        saved: false,
        selected: false,
        name: 'EPSH106092',
        type: 'Réduire intensité lampadaire',
        location: 'Rue Jacques Cartier',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 10.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'SHP',
        foyerType: 'EOLE',
        height: 4,
        validate: null as null,
    },
    {
        id: 52,
        saved: false,
        selected: false,
        name: 'EPNA401094',
        type: 'Réduire intensité lampadaire',
        location: 'Rue du Pen Duick II',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 11.25m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'IMC',
        foyerType: 'ATELIER',
        height: 4.5,
        validate: null as null,
    },
    {
        id: 53,
        saved: false,
        selected: false,
        name: 'EPBG045063',
        type: 'Réduire intensité lampadaire',
        location: 'Route de Saint-Julien de Concelles',
        description:
            'Le lampdaire est entouré par 3 lampadaire(s) dans un rayon de 2.5m.',
        solution:
            "Réduire l'intensité du lampadaire de 15% afin d'économiser de l'énergie.",
        lampType: 'FC',
        foyerType: 'HUBLOT',
        height: 1,
        validate: null as null,
    },
    {
        id: 54,
        saved: false,
        selected: false,
        name: 'EPNA255101',
        type: 'Réduire intensité lampadaire',
        location: 'Rue du Ranzay',
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 10.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'IMC',
        foyerType: 'ELYXE',
        height: 4,
        validate: null as null,
    },
    {
        id: 55,
        saved: false,
        selected: false,
        name: 'EPBG001074',
        type: 'Réduire intensité lampadaire',
        location: "Rue de l'Echalier",
        description:
            'Le lampdaire est entouré par 1 lampadaire(s) dans un rayon de 11.25m.',
        solution:
            "Réduire l'intensité du lampadaire de 5% afin d'économiser de l'énergie.",
        lampType: 'LED',
        foyerType: 'SAGA',
        height: 4.5,
        validate: null as null,
    },
    {
        id: 56,
        saved: false,
        selected: false,
        name: 'EPRZ094062',
        type: 'Réduire intensité lampadaire',
        location: "Rond-Point des Anciens Combattants d'Afrique du No",
        description:
            'Le lampdaire est entouré par 4 lampadaire(s) dans un rayon de 20.0m.',
        solution:
            "Réduire l'intensité du lampadaire de 20% afin d'économiser de l'énergie.",
        lampType: 'SHP',
        foyerType: 'DYANA T2',
        height: 8,
        validate: null as null,
    },
    {
        id: 57,
        saved: false,
        selected: false,
        name: 'EPBG045074',
        type: 'Réduire intensité lampadaire',
        location: 'Route de Saint-Julien de Concelles',
        description:
            'Le lampdaire est entouré par 4 lampadaire(s) dans un rayon de 2.5m.',
        solution:
            "Réduire l'intensité du lampadaire de 20% afin d'économiser de l'énergie.",
        lampType: 'FC',
        foyerType: 'HUBLOT',
        height: 1,
        validate: null as null,
    },
    {
        id: 58,
        saved: false,
        selected: false,
        name: 'EPCA093030',
        type: 'Réduire intensité lampadaire',
        location: 'Avenue Syrma',
        description:
            'Le lampdaire est entouré par 2 lampadaire(s) dans un rayon de 22.5m.',
        solution:
            "Réduire l'intensité du lampadaire de 10% afin d'économiser de l'énergie.",
        lampType: 'SHP',
        foyerType: 'STRADEX 500',
        height: 9,
        validate: null as null,
    },
    {
        id: 59,
        saved: false,
        selected: false,
        name: 'EPCO020038',
        type: 'Augmenter intensité lampadaire',
        location: 'Rue des Meuniers',
        description: 'Le lampdaire est entouré par 2 dans un rayon de 24.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 10% afin d'assurer la sécurité.",
        lampType: 'LED',
        foyerType: 'ISARO LED',
        height: 8,
        validate: null as null,
    },
    {
        id: 60,
        saved: false,
        selected: false,
        name: 'EPOR085012',
        type: 'Augmenter intensité lampadaire',
        location: 'Chemin de la Vigne de Gagné',
        description: 'Le lampdaire est entouré par 1 dans un rayon de 24.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 15% afin d'assurer la sécurité.",
        lampType: 'SHP',
        foyerType: 'IRIDIUM',
        height: 8,
        validate: null as null,
    },
    {
        id: 61,
        saved: false,
        selected: false,
        name: 'EPVT015011',
        type: 'Augmenter intensité lampadaire',
        location: 'Route de Pont Caffino',
        description: 'Le lampdaire est entouré par 1 dans un rayon de 24.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 15% afin d'assurer la sécurité.",
        lampType: 'SHP',
        foyerType: 'COMETE LV2',
        height: 8,
        validate: null as null,
    },
    {
        id: 62,
        saved: false,
        selected: false,
        name: 'EPSH192172',
        type: 'Augmenter intensité lampadaire',
        location: 'Boulevard du Zénith',
        description: 'Le lampdaire est entouré par 1 dans un rayon de 12.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 15% afin d'assurer la sécurité.",
        lampType: 'IMC',
        foyerType: 'METRONOMIS ANNECY',
        height: 4,
        validate: null as null,
    },
    {
        id: 63,
        saved: false,
        selected: false,
        name: 'EPJB010015',
        type: 'Augmenter intensité lampadaire',
        location: 'Rue du Landas',
        description: 'Le lampdaire est entouré par 1 dans un rayon de 30.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 15% afin d'assurer la sécurité.",
        lampType: 'LED',
        foyerType: 'DIGISTREET',
        height: 10,
        validate: null as null,
    },
    {
        id: 64,
        saved: false,
        selected: false,
        name: 'EPBO083041',
        type: 'Augmenter intensité lampadaire',
        location: 'RD 723',
        description: 'Le lampdaire est entouré par 1 dans un rayon de 24.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 15% afin d'assurer la sécurité.",
        lampType: 'SHP',
        foyerType: 'SAPHIR 2',
        height: 8,
        validate: null as null,
    },
    {
        id: 65,
        saved: false,
        selected: false,
        name: 'EPNA162103',
        type: 'Augmenter intensité lampadaire',
        location: 'Rue Charles Roger',
        description: 'Le lampdaire est entouré par 1 dans un rayon de 0.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 15% afin d'assurer la sécurité.",
        lampType: 'FC',
        foyerType: 'BEGA 2078',
        height: 0,
        validate: null as null,
    },
    {
        id: 66,
        saved: false,
        selected: false,
        name: 'EPVT162027',
        type: 'Augmenter intensité lampadaire',
        location: 'Rue Sarah Bernhardt',
        description: 'Le lampdaire est entouré par 2 dans un rayon de 21.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 10% afin d'assurer la sécurité.",
        lampType: 'IM',
        foyerType: 'FUSION 2',
        height: 7,
        validate: null as null,
    },
    {
        id: 67,
        saved: false,
        selected: false,
        name: 'EPNA107009',
        type: 'Augmenter intensité lampadaire',
        location: 'Boulevard Jean Ingres',
        description: 'Le lampdaire est entouré par 3 dans un rayon de 27.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 5% afin d'assurer la sécurité.",
        lampType: 'SHP',
        foyerType: 'BTX',
        height: 9,
        validate: null as null,
    },
    {
        id: 68,
        saved: false,
        selected: false,
        name: 'EPTH018025',
        type: 'Augmenter intensité lampadaire',
        location: 'Rue de la Bussonnière',
        description: 'Le lampdaire est entouré par 3 dans un rayon de 21.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 5% afin d'assurer la sécurité.",
        lampType: 'LED',
        foyerType: 'DIGISTREET',
        height: 7,
        validate: null as null,
    },
    {
        id: 69,
        saved: false,
        selected: false,
        name: 'EPTH006078',
        type: 'Augmenter intensité lampadaire',
        location: 'Rue Montsoreau',
        description: 'Le lampdaire est entouré par 2 dans un rayon de 15.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 10% afin d'assurer la sécurité.",
        lampType: 'LED',
        foyerType: 'R2L2',
        height: 5,
        validate: null as null,
    },
    {
        id: 70,
        saved: false,
        selected: false,
        name: 'EPNA094120',
        type: 'Augmenter intensité lampadaire',
        location: 'Rue Recteur Schmitt',
        description: 'Le lampdaire est entouré par 3 dans un rayon de 24.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 5% afin d'assurer la sécurité.",
        lampType: 'SHP',
        foyerType: 'MC2',
        height: 8,
        validate: null as null,
    },
    {
        id: 71,
        saved: false,
        selected: false,
        name: 'EPCA009005',
        type: 'Augmenter intensité lampadaire',
        location: 'Avenue Jean Bart',
        description: 'Le lampdaire est entouré par 1 dans un rayon de 10.5m.',
        solution:
            "Augmenter l'intensité du lampadaire de 15% afin d'assurer la sécurité.",
        lampType: 'SHP',
        foyerType: 'GAMMA',
        height: 3.5,
        validate: null as null,
    },
    {
        id: 72,
        saved: false,
        selected: false,
        name: 'EPNA296069',
        type: 'Augmenter intensité lampadaire',
        location: 'Rue Lucien Aubert',
        description: 'Le lampdaire est entouré par 3 dans un rayon de 27.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 5% afin d'assurer la sécurité.",
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 9,
        validate: null as null,
    },
    {
        id: 73,
        saved: false,
        selected: false,
        name: 'EPSH033044',
        type: 'Augmenter intensité lampadaire',
        location: 'Impasse Jean Baptiste Guitton',
        description: 'Le lampdaire est entouré par 1 dans un rayon de 18.0m.',
        solution:
            "Augmenter l'intensité du lampadaire de 15% afin d'assurer la sécurité.",
        lampType: 'SHP',
        foyerType: 'SAPHIR',
        height: 6,
        validate: null as null,
    },
];
