export let optimisationTemplateDataBackup = [
    {
        id: 0,
        saved: false,
        selected: false,
        name: 'EPSH109062',
        type: 'Changement bulbe',
        location: 'Rue de Tillay',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ELIPT II 55',
        height: 6,
    },
    {
        id: 1,
        saved: false,
        selected: false,
        name: 'EPSH071142',
        type: 'Changement bulbe',
        location: 'Avenue Jules Vallès',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'PAGODE',
        height: 3.5,
    },
    {
        id: 2,
        saved: false,
        selected: false,
        name: 'EPSH096020',
        type: 'Changement bulbe',
        location: 'Rue Eugénie Cotton',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'INDICE LYRE 500',
        height: 0,
    },
    {
        id: 3,
        saved: false,
        selected: false,
        name: 'EPSO004009',
        type: 'Changement bulbe',
        location: 'Rue de la Guindonnière',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'BOULE Ø570 STRIEE',
        height: 3.5,
    },
    {
        id: 4,
        saved: false,
        selected: false,
        name: 'EPNA156026',
        type: 'Changement bulbe',
        location: "Rue Dos d'Ane",
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'BTX 183',
        height: 10,
    },
    {
        id: 5,
        saved: false,
        selected: false,
        name: 'EPSA042043',
        type: 'Changement bulbe',
        location: 'Rue du Bois Marie',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MODULA G',
        height: 7,
    },
    {
        id: 6,
        saved: false,
        selected: false,
        name: 'EPNA329022',
        type: 'Changement bulbe',
        location: 'Boulevard Jean Moulin',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'LTN1',
        height: 8,
    },
    {
        id: 7,
        saved: false,
        selected: false,
        name: 'EPSH006063',
        type: 'Changement bulbe',
        location: "Rue de l'Oubangui",
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ESTORIL P',
        height: null,
    },
    {
        id: 8,
        saved: false,
        selected: false,
        name: 'EPNA094046',
        type: 'Changement bulbe',
        location: 'Route de la Jonelière',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "TF" en ampoule "LED".',
        lampType: 'TF',
        foyerType: 'HAVANE',
        height: 0,
    },
    {
        id: 9,
        saved: false,
        selected: false,
        name: 'EPBR003001',
        type: 'Changement bulbe',
        location: 'CR 7',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MURENA',
        height: 7,
    },
    {
        id: 10,
        saved: false,
        selected: false,
        name: 'EPSH192055',
        type: 'Changement bulbe',
        location: 'Rue Edith Piaf',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'METRONOMIS ANNECY',
        height: 4,
    },
    {
        id: 11,
        saved: false,
        selected: false,
        name: 'EPBO065004',
        type: 'Changement bulbe',
        location: 'Rue Georges Brassens',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'PESCADOR',
        height: 3.5,
    },
    {
        id: 12,
        saved: false,
        selected: false,
        name: 'EPSH191015',
        type: 'Changement bulbe',
        location: 'Boulevard du Zénith',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IM" en ampoule "LED".',
        lampType: 'IM',
        foyerType: 'MODENA P',
        height: 9,
    },
    {
        id: 13,
        saved: false,
        selected: false,
        name: 'EPBO047016',
        type: 'Changement bulbe',
        location: 'Route de Paimboeuf',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'HARMONY',
        height: 8,
    },
    {
        id: 14,
        saved: false,
        selected: false,
        name: 'EPBO041042',
        type: 'Changement bulbe',
        location: 'Rue de la Croix Jeannette',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'SAPHIR 2',
        height: 8,
    },
    {
        id: 15,
        saved: false,
        selected: false,
        name: 'EPBO023006',
        type: 'Changement bulbe',
        location: 'Rue Jules Vallès',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MURENA',
        height: 9,
    },
    {
        id: 16,
        saved: false,
        selected: false,
        name: 'EPVT142027',
        type: 'Changement bulbe',
        location: 'Avenue du Bois Doux',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'KIO',
        height: 3.5,
    },
    {
        id: 17,
        saved: false,
        selected: false,
        name: 'EPBY038003',
        type: 'Changement bulbe',
        location: 'Rue des Aubépines',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IJB',
        height: 3.5,
    },
    {
        id: 18,
        saved: false,
        selected: false,
        name: 'EPLP021001',
        type: 'Changement bulbe',
        location: 'Rue de la Bréhannerie',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 9,
    },
    {
        id: 19,
        saved: false,
        selected: false,
        name: 'EPST068008',
        type: 'Changement bulbe',
        location: 'Rue Robert Douineau',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 9',
        height: 9,
    },
    {
        id: 20,
        saved: false,
        selected: false,
        name: 'EPVT008105',
        type: 'Changement bulbe',
        location: 'Rue des Fraîches',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 9,
    },
    {
        id: 21,
        saved: false,
        selected: false,
        name: 'EPBO094096',
        type: 'Changement bulbe',
        location: 'Place des Centaures',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'METRONOMIS BERLIN',
        height: 4.5,
    },
    {
        id: 22,
        saved: false,
        selected: false,
        name: 'EPLM007009',
        type: 'Changement bulbe',
        location: 'Passage du Bosquet',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'PALLAS 400',
        height: 4,
    },
    {
        id: 23,
        saved: false,
        selected: false,
        name: 'EPST042038',
        type: 'Changement bulbe',
        location: 'Rue du Petit Anjou',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'NANTUA',
        height: 8,
    },
    {
        id: 24,
        saved: false,
        selected: false,
        name: 'EPIN003013',
        type: 'Changement bulbe',
        location: 'Place de la Martinière',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'LB 60',
        height: 6,
    },
    {
        id: 25,
        saved: false,
        selected: false,
        name: 'EPNA214186',
        type: 'Changement bulbe',
        location: 'Rue de Brest',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IM" en ampoule "LED".',
        lampType: 'IM',
        foyerType: null,
        height: 3.700000047683716,
    },
    {
        id: 26,
        saved: false,
        selected: false,
        name: 'EPBR007008',
        type: 'Changement bulbe',
        location: 'Rue de la Chaussée',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 0,
    },
    {
        id: 27,
        saved: false,
        selected: false,
        name: 'EPSH034137',
        type: 'Changement bulbe',
        location: 'Rue du Lieutenant Mouillie',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'TRANSCUBE',
        height: 3.5,
    },
    {
        id: 28,
        saved: false,
        selected: false,
        name: 'EPLP030009',
        type: 'Changement bulbe',
        location: 'Rue du Capitaine Guérin',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'DISCERA 600',
        height: 6,
    },
    {
        id: 29,
        saved: false,
        selected: false,
        name: 'EPOR064012',
        type: 'Changement bulbe',
        location: 'Avenue de la Bugallière',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 9,
    },
    {
        id: 30,
        saved: false,
        selected: false,
        name: 'EPSH120013',
        type: 'Changement bulbe',
        location: 'Rue Docteur Albert Schweitzer',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'SWAP 2 STORIA',
        height: 3.5,
    },
    {
        id: 31,
        saved: false,
        selected: false,
        name: 'EPSO093039',
        type: 'Changement bulbe',
        location: 'Rue de la Haute Lande',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'CYCLONE',
        height: 6,
    },
    {
        id: 32,
        saved: false,
        selected: false,
        name: 'EPNA365135',
        type: 'Changement bulbe',
        location: 'Boulevard Léon Jouhaux',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'SAPHIR',
        height: 7,
    },
    {
        id: 33,
        saved: false,
        selected: false,
        name: 'EPSA035011',
        type: 'Changement bulbe',
        location: 'Rue de Beauséjour',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'MINI CITYSOUL',
        height: 5,
    },
    {
        id: 34,
        saved: false,
        selected: false,
        name: 'EPNA096073',
        type: 'Changement bulbe',
        location: 'Rue des Boers',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM',
        height: 0,
    },
    {
        id: 35,
        saved: false,
        selected: false,
        name: 'EPBY011037',
        type: 'Changement bulbe',
        location: 'Avenue Notre-Dame de la Route',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MURENA',
        height: 7,
    },
    {
        id: 36,
        saved: false,
        selected: false,
        name: 'EPBG052019',
        type: 'Changement bulbe',
        location: 'Rue du Général Leclerc',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'EUROPA',
        height: 6,
    },
    {
        id: 37,
        saved: false,
        selected: false,
        name: 'EPSO021048',
        type: 'Changement bulbe',
        location: 'Rue Hippolyte Derouet',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "MBF" en ampoule "LED".',
        lampType: 'MBF',
        foyerType: 'POLYCUBE OR',
        height: 3.5,
    },
    {
        id: 38,
        saved: false,
        selected: false,
        name: 'EPOR065064',
        type: 'Changement bulbe',
        location: 'Place de la Liberté',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'BTX 183 LYRE',
        height: 8,
    },
    {
        id: 39,
        saved: false,
        selected: false,
        name: 'EPST067032',
        type: 'Changement bulbe',
        location: 'Rue des Mortiers',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 9',
        height: 8,
    },
    {
        id: 40,
        saved: false,
        selected: false,
        name: 'EPOR036079',
        type: 'Changement bulbe',
        location: 'Rue de Solay',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'THAIS',
        height: 9,
    },
    {
        id: 41,
        saved: false,
        selected: false,
        name: 'EPVT080023',
        type: 'Changement bulbe',
        location: 'Chemin des Perdriaux',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'PILOTE T2',
        height: 8,
    },
    {
        id: 42,
        saved: false,
        selected: false,
        name: 'EPSH067026',
        type: 'Changement bulbe',
        location: 'Rue Camille Pissarro',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'KIO',
        height: 4,
    },
    {
        id: 43,
        saved: false,
        selected: false,
        name: 'EPOR011017',
        type: 'Changement bulbe',
        location: 'Allée de la Sarthe',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'BTX',
        height: 6,
    },
    {
        id: 44,
        saved: false,
        selected: false,
        name: 'EPVT069073',
        type: 'Changement bulbe',
        location: 'Place du Beau Verger',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'OLIVIO 300',
        height: 10.600000381469727,
    },
    {
        id: 45,
        saved: false,
        selected: false,
        name: 'EPNA096081',
        type: 'Changement bulbe',
        location: 'Rue du Coudray',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'SAPHIR',
        height: 9,
    },
    {
        id: 46,
        saved: false,
        selected: false,
        name: 'EPCH001142',
        type: 'Changement bulbe',
        location: "Rue de l'Erdre",
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'GENERATEUR FIBRE OPTIQUE BL2',
        height: 0,
    },
    {
        id: 47,
        saved: false,
        selected: false,
        name: 'EPNA085038',
        type: 'Changement bulbe',
        location: 'Boulevard Louis Millet',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 6,
    },
    {
        id: 48,
        saved: false,
        selected: false,
        name: 'EPSH150020',
        type: 'Changement bulbe',
        location: 'Rue du Havre',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'KIO',
        height: 4,
    },
    {
        id: 49,
        saved: false,
        selected: false,
        name: 'EPNA361019',
        type: 'Changement bulbe',
        location: 'Quai Malakoff',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'PFL 240',
        height: 9,
    },
    {
        id: 50,
        saved: false,
        selected: false,
        name: 'EPNA356047',
        type: 'Changement bulbe',
        location: 'Rue de la Fauvette',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM',
        height: 0,
    },
    {
        id: 51,
        saved: false,
        selected: false,
        name: 'EPLP002028',
        type: 'Changement bulbe',
        location: 'Allée des Mimosas',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ESTORIL P',
        height: 9,
    },
    {
        id: 52,
        saved: false,
        selected: false,
        name: 'EPBO078005',
        type: 'Changement bulbe',
        location: 'Rue du Capitaine Némo',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 9',
        height: 5,
    },
    {
        id: 53,
        saved: false,
        selected: false,
        name: 'EPST054040',
        type: 'Changement bulbe',
        location: 'Rue Jean Mermoz',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'SAPHIR',
        height: 8.600000381469727,
    },
    {
        id: 54,
        saved: false,
        selected: false,
        name: 'EPBO055070',
        type: 'Changement bulbe',
        location: 'Avenue Neptune',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 10,
    },
    {
        id: 55,
        saved: false,
        selected: false,
        name: 'EPST097009',
        type: 'Changement bulbe',
        location: 'Rue des Fresches',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MODULA',
        height: 5,
    },
    {
        id: 56,
        saved: false,
        selected: false,
        name: 'EPBO027026',
        type: 'Changement bulbe',
        location: 'Rue de la Grande Ouche',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ELIPT 55',
        height: 8,
    },
    {
        id: 57,
        saved: false,
        selected: false,
        name: 'EPBY033036',
        type: 'Changement bulbe',
        location: 'Allée de Grand-Lieu',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 9,
    },
    {
        id: 58,
        saved: false,
        selected: false,
        name: 'EPVT001113',
        type: 'Changement bulbe',
        location: 'Impasse André Gouin',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'KIO',
        height: 3.5,
    },
    {
        id: 59,
        saved: false,
        selected: false,
        name: 'EPVT031036',
        type: 'Changement bulbe',
        location: 'Rue du Bois Hardy',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 8,
    },
    {
        id: 60,
        saved: false,
        selected: false,
        name: 'EPBO049013',
        type: 'Changement bulbe',
        location: "Rue de l'Aéronautique",
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MURENA',
        height: 10,
    },
    {
        id: 61,
        saved: false,
        selected: false,
        name: 'EPRZ010030',
        type: 'Changement bulbe',
        location: 'Rue Paul Cézanne',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'MURENA',
        height: 6,
    },
    {
        id: 62,
        saved: false,
        selected: false,
        name: 'EPOR059075',
        type: 'Changement bulbe',
        location: 'Rue des Baillauds',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'KIO',
        height: 4.5,
    },
    {
        id: 63,
        saved: false,
        selected: false,
        name: 'EPJB005047',
        type: 'Changement bulbe',
        location: 'Rue de la Perche',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ESTORIL P',
        height: 10,
    },
    {
        id: 64,
        saved: false,
        selected: false,
        name: 'EPLP021003',
        type: 'Changement bulbe',
        location: 'Rue de la Bréhannerie',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: null,
    },
    {
        id: 65,
        saved: false,
        selected: false,
        name: 'EPBO083098',
        type: 'Changement bulbe',
        location: 'Route de Paimboeuf',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ALURA DIRECT',
        height: 3.5999999046325684,
    },
    {
        id: 66,
        saved: false,
        selected: false,
        name: 'EPST227018',
        type: 'Changement bulbe',
        location: 'Rue du Périgord',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 9',
        height: 6,
    },
    {
        id: 67,
        saved: false,
        selected: false,
        name: 'EPCO034036',
        type: 'Changement bulbe',
        location: 'Rue Pasteur',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 9',
        height: 8,
    },
    {
        id: 68,
        saved: false,
        selected: false,
        name: 'EPLP002052',
        type: 'Changement bulbe',
        location: 'Allée des Tulipes',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'CITYSOUL MINI',
        height: 5,
    },
    {
        id: 69,
        saved: false,
        selected: false,
        name: 'EPBO053099',
        type: 'Changement bulbe',
        location: 'Rue Jean Emile Laboureur',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'NEOS 1',
        height: 7,
    },
    {
        id: 70,
        saved: false,
        selected: false,
        name: 'EPOR064028',
        type: 'Changement bulbe',
        location: 'Rond-Point du Bois Cesbron',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 10,
    },
    {
        id: 71,
        saved: false,
        selected: false,
        name: 'EPRZ010072',
        type: 'Changement bulbe',
        location: 'Rue Charles Rivière',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IM" en ampoule "LED".',
        lampType: 'IM',
        foyerType: 'LEMNIS',
        height: 7,
    },
    {
        id: 72,
        saved: false,
        selected: false,
        name: 'EPOR064060',
        type: 'Changement bulbe',
        location: 'Rond-Point du Bois Cesbron',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MODULA P',
        height: 6,
    },
    {
        id: 73,
        saved: false,
        selected: false,
        name: 'EPCH130028',
        type: 'Changement bulbe',
        location: 'Rue des Alizés',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'EUROPA',
        height: 8,
    },
    {
        id: 74,
        saved: false,
        selected: false,
        name: 'EPSH132054',
        type: 'Changement bulbe',
        location: "Avenue de l'Abbé Henri Grégoire",
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ELIPT II 55',
        height: 6,
    },
    {
        id: 75,
        saved: false,
        selected: false,
        name: 'EPOR013024',
        type: 'Changement bulbe',
        location: 'Rue de la Garenne',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MODULA G',
        height: 10,
    },
    {
        id: 76,
        saved: false,
        selected: false,
        name: 'EPNA361024',
        type: 'Changement bulbe',
        location: 'Quai Malakoff',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'PIXEL',
        height: 9,
    },
    {
        id: 77,
        saved: false,
        selected: false,
        name: 'EPSH037059',
        type: 'Changement bulbe',
        location: 'Rue des Robiniers',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'KIO',
        height: 4,
    },
    {
        id: 78,
        saved: false,
        selected: false,
        name: 'EPSH206073',
        type: 'Changement bulbe',
        location: 'Rue Victor Schoelcher',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IM" en ampoule "LED".',
        lampType: 'IM',
        foyerType: 'METRONOMIS ANNECY',
        height: 3.5,
    },
    {
        id: 79,
        saved: false,
        selected: false,
        name: 'EPIN004047',
        type: 'Changement bulbe',
        location: 'Rue de la Gare',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IM" en ampoule "LED".',
        lampType: 'IM',
        foyerType: 'BERLIN CDS 570',
        height: 4.5,
    },
    {
        id: 80,
        saved: false,
        selected: false,
        name: 'EPIN007054',
        type: 'Changement bulbe',
        location: 'Rue de Bellevue',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 8,
    },
    {
        id: 81,
        saved: false,
        selected: false,
        name: 'EPOR070029',
        type: 'Changement bulbe',
        location: 'Rue Léon Gaumont',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'AUSTRALE 73',
        height: 10,
    },
    {
        id: 82,
        saved: false,
        selected: false,
        name: 'EPSA008058',
        type: 'Changement bulbe',
        location: 'Rue de Bretagne',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IM" en ampoule "LED".',
        lampType: 'IM',
        foyerType: 'MAYA MIDI',
        height: 8,
    },
    {
        id: 83,
        saved: false,
        selected: false,
        name: 'EPOR004058',
        type: 'Changement bulbe',
        location: 'Rue Bonnetable',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IJB',
        height: 9,
    },
    {
        id: 84,
        saved: false,
        selected: false,
        name: 'EPCH014023',
        type: 'Changement bulbe',
        location: 'Rue Maurice Ravel',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'RIVIERA 2',
        height: 8,
    },
    {
        id: 85,
        saved: false,
        selected: false,
        name: 'EPOR003031',
        type: 'Changement bulbe',
        location: 'Rue de la Patache',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ESTORIL P',
        height: 8,
    },
    {
        id: 86,
        saved: false,
        selected: false,
        name: 'EPNA267077',
        type: 'Changement bulbe',
        location: 'Rue Alfred Kastler',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "IMC" en ampoule "LED".',
        lampType: 'IMC',
        foyerType: 'NEOS 2',
        height: 7.599999904632568,
    },
    {
        id: 87,
        saved: false,
        selected: false,
        name: 'EPNA124119',
        type: 'Changement bulbe',
        location: 'Rue des Petits Coteaux',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 9',
        height: 7,
    },
    {
        id: 88,
        saved: false,
        selected: false,
        name: 'EPNA132052',
        type: 'Changement bulbe',
        location: 'Rue des Plantes',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 10',
        height: 9,
    },
    {
        id: 89,
        saved: false,
        selected: false,
        name: 'EPRZ021003',
        type: 'Changement bulbe',
        location: 'Place Renoir',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'ORACLE T1',
        height: 8,
    },
    {
        id: 90,
        saved: false,
        selected: false,
        name: 'EPSH212015',
        type: 'Changement bulbe',
        location: 'Rue du Docteur Alfred Corlay',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MODENA P',
        height: null,
    },
    {
        id: 91,
        saved: false,
        selected: false,
        name: 'EPNA333096',
        type: 'Changement bulbe',
        location: 'Rue de Wassy',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'AVENUE F',
        height: 3.5999999046325684,
    },
    {
        id: 92,
        saved: false,
        selected: false,
        name: 'EPNA354044',
        type: 'Changement bulbe',
        location: 'Rue Francis de Pressensé',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'SAPHIR',
        height: 0,
    },
    {
        id: 93,
        saved: false,
        selected: false,
        name: 'EPNA365123',
        type: 'Changement bulbe',
        location: 'Rue Louis Guilloux',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'MODULA P',
        height: 9,
    },
    {
        id: 94,
        saved: false,
        selected: false,
        name: 'EPOR036071',
        type: 'Changement bulbe',
        location: 'Rue de Solay',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'THAIS',
        height: 9,
    },
    {
        id: 95,
        saved: false,
        selected: false,
        name: 'EPLP007016',
        type: 'Changement bulbe',
        location: 'Rue du Commandant Charcot',
        description: 'Ampoule LED moins consommatrice.',
        solution: 'Changer l\'ampoule "SHP" en ampoule "LED".',
        lampType: 'SHP',
        foyerType: 'IRIDIUM 9',
        height: 5,
    },
    {
        id: 96,
        saved: false,
        selected: false,
        name: 'EPCH144022',
        type: 'Allumer lampadaire',
        location: 'Rue du Roty',
        description: 'Coucher du soleil à 17:56',
        solution: 'Allumer le lampadaire EPCH144022 à partir de 17:56',
        lampType: 'SHP',
        foyerType: 'DECOSTREET 1',
        height: 4,
    },
    {
        id: 97,
        saved: false,
        selected: false,
        name: 'EPSH132079',
        type: 'Allumer lampadaire',
        location: 'Allée William Harvey',
        description: 'Coucher du soleil à 17:56',
        solution: 'Allumer le lampadaire EPSH132079 à partir de 17:56',
        lampType: 'SHP',
        foyerType: 'ELYXE',
        height: 4,
    },
    {
        id: 98,
        saved: false,
        selected: false,
        name: 'EPOR088035',
        type: 'Allumer lampadaire',
        location: 'Route de Vannes',
        description: 'Coucher du soleil à 17:56',
        solution: 'Allumer le lampadaire EPOR088035 à partir de 17:56',
        lampType: 'IMC',
        foyerType: 'HESTIA MIDI',
        height: 8,
    },
    {
        id: 99,
        saved: false,
        selected: false,
        name: 'EPOR089104',
        type: 'Allumer lampadaire',
        location: 'Rue du Bignon',
        description: 'Coucher du soleil à 17:56',
        solution: 'Allumer le lampadaire EPOR089104 à partir de 17:56',
        lampType: 'SHP',
        foyerType: 'ORIENT',
        height: 3.5,
    },
];
